// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqrvQeXzepeFUYZuPmmIGWnZIUYkIzezc',
    appId: '1:645734619239:web:c766ef30f45cacb2f3dcc2',
    messagingSenderId: '645734619239',
    projectId: 'oiecdb',
    authDomain: 'oiecdb.firebaseapp.com',
    storageBucket: 'oiecdb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMaaxndZwA4Nd9Z7KcsMGaZ7mFm-uF0bY',
    appId: '1:645734619239:android:3d57fe4d00e02d8df3dcc2',
    messagingSenderId: '645734619239',
    projectId: 'oiecdb',
    storageBucket: 'oiecdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVCVHOvP-yprl0rgL5HgR5O9pQVwHwl2I',
    appId: '1:645734619239:ios:2a132c4ef19d7f42f3dcc2',
    messagingSenderId: '645734619239',
    projectId: 'oiecdb',
    storageBucket: 'oiecdb.appspot.com',
    iosBundleId: 'com.example.oiecApp',
  );
}
