name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'latest'

    - name: Install dependencies
      run: |
        cd oiec_app
        flutter pub get

    - name: Build APK
      run: |
        cd oiec_app
        flutter build apk --release

  build_ios:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'latest'

    - name: Install dependencies
      run: |
        cd oiec_app
        flutter pub get

    - name: Build iOS
      run: |
        cd oiec_app
        flutter build ios --release --no-codesign