name: OIEC App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'

    - name: Install dependencies
      run: |
        cd oiec_app
        flutter pub get

    - name: Build APK
      run: |
        cd oiec_app
        flutter build apk --release
    
    - name: Upload APK to root directory
      uses: actions/upload-artifact@v2
      with:
        name: OIECApp-release
        path: oiec_app/build/app/outputs/flutter-apk/app-release.apk

  build_ios:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'

    - name: Install dependencies
      run: |
        cd oiec_app
        flutter pub get

    - name: Build iOS
      run: |
        cd oiec_app
        flutter build ios --release --no-codesign